import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ilya
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        super("Calculator");
        initComponents();
        btnUpdate.setVisible(false);
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Nametxt = new javax.swing.JTextField();
        Surnametxt = new javax.swing.JTextField();
        UserNametxt = new javax.swing.JTextField();
        Passwordtxt = new javax.swing.JTextField();
        Addbtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        projectBox = new javax.swing.JComboBox<>();
        JuniorRb = new javax.swing.JRadioButton();
        MiddleRb = new javax.swing.JRadioButton();
        SeniorRb = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        Cancelbtn = new javax.swing.JButton();
        hoursTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        EIDtxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Name:");

        jLabel3.setText("Surname:");

        jLabel4.setText("UserName:");

        jLabel5.setText("Password:");

        Addbtn.setText("Add");
        Addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbtnActionPerformed(evt);
            }
        });

        jLabel6.setText("Select your project:");

        jCheckBox1.setText("I am the project manager");

        projectBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coffee machine", "Computer game", "Cloud technology" }));

        buttonGroup1.add(JuniorRb);
        JuniorRb.setSelected(true);
        JuniorRb.setText("Junior");

        buttonGroup1.add(MiddleRb);
        MiddleRb.setText("Middle");

        buttonGroup1.add(SeniorRb);
        SeniorRb.setText("Senior");

        jLabel7.setText("Choose your level:");

        Cancelbtn.setText("Cancel");
        Cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelbtnActionPerformed(evt);
            }
        });

        jLabel8.setText("Type the number of worked hours:");

        btnUpdate.setText("Update");
        btnUpdate.setEnabled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel1.setText("EID:");

        EIDtxt.setName("EIDtxt"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MiddleRb)
                            .addComponent(JuniorRb)
                            .addComponent(SeniorRb)))
                    .addComponent(hoursTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(53, 53, 53)
                        .addComponent(Cancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(projectBox, 0, 315, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addGap(35, 35, 35)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Passwordtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                                .addComponent(UserNametxt)
                                .addComponent(Surnametxt)
                                .addComponent(Nametxt)
                                .addComponent(EIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(EIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Surnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(UserNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hoursTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(projectBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(JuniorRb))
                .addGap(18, 18, 18)
                .addComponent(MiddleRb)
                .addGap(32, 32, 32)
                .addComponent(SeniorRb)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbtnActionPerformed
       try{
           
           String str=hoursTxt.getText();
        int h=Integer.parseInt(str);
       
        
        double jp=0, mp=0, sp=0,sal=0;
        if (h>=0&&h<=265)
        {
            int am=0;
            if (jCheckBox1.isSelected()) am=300;
            if (projectBox.getSelectedItem()=="Coffee machine")
            {
                jp=1.7; mp=5.2; sp=7.3;
            }
            if (projectBox.getSelectedItem()=="Computer game")
            {
                jp=1.4; mp=5.5; sp=1.3;
            }
            if (projectBox.getSelectedItem()=="Cloud technology")
                jp=2.7; mp=6.2; sp=12.3;
        if (JuniorRb.isSelected()) sal=jp*h+am;
        if (MiddleRb.isSelected()) sal=mp*h+am;
        if (SeniorRb.isSelected()) sal=sp*h+am;
        Connection con=sqlConnection.dbConnector();
        Statement st;
        try{
            String query="insert into employeeInfo (Name, Surname, Project, Salary, UserName, Password) values  ('"+Nametxt.getText()+"', '"+Surnametxt.getText()+"', '"+projectBox.getSelectedItem()+"', '"+sal+"', '"+UserNametxt.getText()+"','"+CryptWithMD5.cryptWithMD5(Passwordtxt.getText())+"');";
            st=con.createStatement();
            if (st.executeUpdate(query)==1)
            {dispose(); EmployeeInfo empli=new EmployeeInfo(); empli.setVisible(true);};
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Type an integer unsigned number from 0 till 265");
        }}catch(NumberFormatException e)
               {
                   JOptionPane.showMessageDialog(null, e);
               }
    }//GEN-LAST:event_AddbtnActionPerformed

    private void CancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelbtnActionPerformed
        dispose();
        EmployeeInfo empl=new EmployeeInfo();
        empl.setVisible(true);
    }//GEN-LAST:event_CancelbtnActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
         try{
             
           String str=hoursTxt.getText();
        int h=Integer.parseInt(str);
       
        
        double jp=0, mp=0, sp=0,sal=0;
        if (h>=0&&h<=265)
        {
            int am=0;
            if (jCheckBox1.isSelected()) am=300;
            if (projectBox.getSelectedItem()=="Coffee machine")
            {
                jp=1.7; mp=5.2; sp=7.3;
            }
            if (projectBox.getSelectedItem()=="Computer game")
            {
                jp=1.4; mp=5.5; sp=1.3;
            }
            if (projectBox.getSelectedItem()=="Cloud technology")
                jp=2.7; mp=6.2; sp=12.3;
        if (JuniorRb.isSelected()) sal=jp*h+am;
        if (MiddleRb.isSelected()) sal=mp*h+am;
        if (SeniorRb.isSelected()) sal=sp*h+am;
        Connection con=sqlConnection.dbConnector();
        Statement st;
        try{
            String query="update employeeInfo set Name='"+Nametxt.getText()+"', Surname='"+Surnametxt.getText()+"', Project='"+projectBox.getSelectedItem()+"', Salary='"+sal+"', UserName='"+UserNametxt.getText()+"', Password='"+CryptWithMD5.cryptWithMD5(Passwordtxt.getText())+"' where EID="+EIDtxt.getText()+";";
            st=con.createStatement();
            if (st.executeUpdate(query)==1)
            {dispose(); EmployeeInfo empli=new EmployeeInfo(); empli.setVisible(true);};
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Type an integer unsigned number from 0 till 265");
        }}catch(NumberFormatException e)
               {
                   JOptionPane.showMessageDialog(null, e);
               }
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Addbtn;
    private javax.swing.JButton Cancelbtn;
    public javax.swing.JTextField EIDtxt;
    private javax.swing.JRadioButton JuniorRb;
    private javax.swing.JRadioButton MiddleRb;
    public javax.swing.JTextField Nametxt;
    public javax.swing.JTextField Passwordtxt;
    private javax.swing.JRadioButton SeniorRb;
    public javax.swing.JTextField Surnametxt;
    public javax.swing.JTextField UserNametxt;
    public javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JTextField hoursTxt;
    private javax.swing.JCheckBox jCheckBox1;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JComboBox<String> projectBox;
    // End of variables declaration//GEN-END:variables
}
